gcloud compute tpus tpu-vm ssh ${TPU_NAME} \
  --zone=${ZONE} \
  --project=${PROJECT_ID} \
  --worker=all \
  --command="PJRT_DEVICE=TPU python3 ~/models/train_deberta.py  \
  --data_dir=gs://t2t_data \
  --batch_size=128 \
  --base_learning_rate=0.0001 \
  --decay_type=cosine \
  --decay_steps=1280 \
  --num_epochs=1 2>&1 | tee ~/logs.txt"
